### ISSUE TITLE
Include systemd unit overrides

### ISSUE THREAD

**Issue by cryzed** [graysky2/lostfiles#20]
Currently you are [excluding /etc/systemd/system](https://github.com/graysky2/lostfiles/blob/master/lostfiles#L74) entirely, however there might be important override unit files in there, for example: `/etc/systemd/system/postgresql.service.d/override.conf` (same goes for `/etc/systemd/user` I'd imagine).

I am using lostfiles to regularly [create](https://github.com/cryzed/bin/blob/master/backup-system) very quick backups of my core system configuration -- meaning configuration files I either had to manually create or backup files I modified. The various override configuration files, are definitely part of that setup, however my script would obviously miss them because they are all pruned.

I am not sure on which criteria you are filtering the results, so maybe this addition really doesn't belong in this script, let me know.

**Comment by graysky2** [comment]
Since the symlinks and files under `/etc/systemd/system` aren't technically owned by a package, it seems right to exclude that location.. after all:

>A simple script that identifies files not owned and not created by any Arch Linux package.

**Comment by cryzed** [comment]
So because an application contained in an Arch Linux package, in this case systemd, created the files, they should be ignored? This is the only way I can interpret your sentence and come to the same conclusion.

If you didn't mean that, I would say that it seems like you are arguing against your own point? The script's goal is to:

> identif[y] files not owned and not created by any Arch Linux package.

Since the overrides in `/etc/systemd/system/.../override.conf` are created by systemd itself, they are "not owned and not created by any Arch Linux package". The issue is here what exactly is meant by "created by any Arch Linux package": The side-effects of install-scripts during package installations? Or as assumed above, simply created by an application that is owned by an Arch Linux package?

**Comment by graysky2** [comment]
> So because an application contained in an Arch Linux package, in this case systemd, created the files, they should be ignored? This is the only way I can interpret your sentence and come to the same conclusion.

I believe that was the original intent of the script... if the package didn't directly provide the file or if it subsequently did not create the file (thus indirectly providing it), the script will show these to the user so he/she can decide if the file is safe to remove the filesystem

**Comment by cryzed** [comment]
Alright, I'll manually add these paths to my backup script then. Thank you for your quick replies.

**Comment by graysky2** [comment]
No problem.  You can fork the repo and make your modifications.  Then periodically check this repo and simply manually merge anything you like into your version.  Gotta love git.

**Comment by cryzed** [comment]
I [updated](https://github.com/cryzed/bin/blob/master/backup-system#L43) my script instead -- your script does exactly what it is supposed to do, I just wasn't exactly sure what that was apparently. Thank you for all the work you do by the way, I use quite a bit of it.

**Comment by graysky2** [comment]
You're welcome.  Enjoy.
