### ISSUE TITLE
Find warning when using strict mode

### ISSUE THREAD

**Issue by glitsj16** [graysky2/lostfiles#23]
Hi, after latest update I get a 'find' error/warning when using strict mode:

$ sudo /usr/bin/lostfiles strict
find: expected an expression after '-o'
...

In 'relaxed' mode everything runs fine. Looking at the code this can be easily fixed with the below patch:
```
--- a/lostfiles
+++ b/lostfiles
@@ -45,7 +45,7 @@
     -wholename '/var/lib' -prune -o \
     -wholename '/var/log' -prune -o \
     -wholename '/var/run' -prune -o \
-    -wholename '/var/spool' -prune -o \
+    -wholename '/var/spool' -prune \) | sort -u \
     ) | sed -e 's|^\t||;'
 }
```

Regards.

**Comment by graysky2** [comment]
Thanks, hasty edit on my part.
