### ISSUE TITLE
Only search folders in the Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by refola** [graysky2/lostfiles#24]
When I ran the script, it choked on the thousands of btrfs snapshots my backup script made under `/hdds/snapshots`. Since `/hdds` is a separate mountpoint, I was able to change the `find` commands to `find / -xdev -not [...]` as a personal workaround. But that would break the script for people who have, e.g., `/opt` on a separate filesystem.

As far as I know, it's standard practice to mount extra filesystems in folders outside the Filesystem Hierarchy Standard (the closest I could find to a recommendation was that `/media` and `/mnt` are for [temporarily-mounted](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#mediaMountPoint) partitions). Anything in these 'extra' mountpoints is guaranteed not to be owned by any FHS-following package, so there doesn't seem to be much point searching there.

I know this would about double or triple the code complexity, but I think the correct fix is for `lostfiles` to search only specific directories in the FHS. Specifically, this would be `/boot`, `/bin`, `/etc`, `/lib*`, `/opt`, `/sbin`, `/usr`, and `/var` (i.e., every FHS-specified directory that you're not already excluding). Then adding a simple `ls -A /` would suffice to alert users of stray root-level files.

**Comment by graysky2** [comment]
I'm not sure of an easy way to do what you're asking either... in your case, you might just settle on forking the script and manually updating it with your addition to ignore /hdds.

**Comment by refola** [comment]
I just wrapped the `relaxed` and `strict` functions with a `search` function that loops thru valid FHS-specified places where package-owned files are expected, then manually checks everything directly under `/` and lists the ones where packages shouldn't be installed (e.g., custom mount paints). I'm submitting a pull request.
