### ISSUE TITLE
More directories to exclude

### ISSUE THREAD

**Issue by z3ntu** [graysky2/lostfiles#27]
`/var/cache/` & `/var/tmp/`

Thanks for the great application, just did some cleanup 👍

**Comment by graysky2** [comment]
PRs welcomed.

**Comment by z3ntu** [comment]
Just noticed, that these directories are actually excluded in the relaxed state. But I think they should be in strict too... If you agree, I will send a PR :) (if you don't do it first yourself)

**Comment by graysky2** [comment]
The point of the two modes was to allow for some flexibility; as it stands one could or could not select them, no?  Leaving it as-is would be my vote.

**Comment by z3ntu** [comment]
At least put something in the README which explains the strict and relaxed modes and which one you should use. (would be quite helpful for new people tbh) :)
