### ISSUE TITLE
Exclude .pyc Files?

### ISSUE THREAD

**Issue by dalliard** [graysky2/lostfiles#28]
I noticed, that I have some .pyc Files that aren't owned by a Package. They get generated if a Python File is executed. Is it a good Idea to exclude them? Or should I get in contact with the Owner of the Package? Not sure how that works. Thanks for the great Package!!

**Comment by graysky2** [comment]
Unless you're running your python scripts as root, and assuming these are under non-user spaces such as /usr or the like, something is off with your filesystem permissions in a big way.

**Comment by dalliard** [comment]
238 Entries all from App Engine like this:

````
/opt/google-appengine-go/google/appengine/api/api_base_pb.pyc
````

**Comment by graysky2** [comment]
/opt is not something the script is currently ignoring.  I guess a line could be added pointing to ignore these in the relaxed setting.

**Comment by graysky2** [comment]
Please try https://github.com/graysky2/lostfiles/releases/tag/v3.26 and reopen if it doesn't fix for you

**Comment by dalliard** [comment]
Ah sorry my bad. There are other Folders with .pyc Files. [Here](https://gist.github.com/dalliard/59c337397c9761012cb2b45ffa0b5443). All from App Engine.

**Comment by graysky2** [comment]
PRs are welcomed.
