### ISSUE TITLE
linux.preset

### ISSUE THREAD

**Issue by dschrempf** [graysky2/lostfiles#47]
Hi!

Thank you for this amazing script!

I have a short question. The file =/etc/mkinitcpio.d/linux.preset= is reported as lost, but I think it should not be deleted. Can you confirm this and probbaly add an appropirate ignore pattern?

Thank you for your help,
Dominik

**Comment by graysky2** [comment]
I think `foo.preset` gets created by a pacman hook on installation.  Technically no package owns them but they are required/should not be deleted.

**Comment by graysky2** [comment]
Well, `foo.preset` gets created by a pacman hook on installation (`/usr/share/libalpm/scripts/mkinitcpio-install` is the script the hook calls).  Technically no package owns them but they are required/should not be deleted.

**Comment by dschrempf** [comment]
Thank you!

On November 26, 2020 2:50:28 PM GMT+01:00, graysky <notifications@github.com> wrote:
>Closed #47 via b88bfed81b324a58a73aa7d92db78cc859def5e3.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/graysky2/lostfiles/issues/47#event-4042625476

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
