### ISSUE TITLE
`find: '/boot': No such file or directory` but `/boot` is no longer a required name according to `systemd-boot`.

### ISSUE THREAD

**Issue by enihcam** [graysky2/lostfiles#59]
```bash
$ sudo lostfiles
find: '/boot': No such file or directory
```

https://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html
> The ESP is mounted to /boot/ if that directory exists and is not used for XBOOTLDR, and otherwise to /efi/.

for more details regarding to /efi:
https://www.freedesktop.org/software/systemd/man/systemd-boot.html

**Comment by graysky2** [comment]
My suspicion is that the majority of users have `/boot` so a hacky fix is to just redirect the harmless output to `/dev/null`

**Comment by enihcam** [comment]
suppression of harmless output is one thing, but you still need to check on /efi, right? :)

**Comment by graysky2** [comment]
I can add it but I only have experience using grub which creates `/eft/EFI/grub2/grubx64.efi` I am not sure about other efi boot utils.
