### ISSUE TITLE
4 Files Stay No Matter What I Do

### ISSUE THREAD

**Issue by nateisch** [graysky2/lostfiles#8]
Hey, great little script. Maybe you can just help  me with this "little" problem. No matter what I do, these 4 files stay and of course, they are there for a reason. Maybe you can exclude them or help me to get rid of them. It seems like they get created everytime I reboot or restart my machine.

The files are:

* /etc/os-release
* /etc/.pwd.lock
* /etc/.updated
* /var/.updated

Thanks - this isn't really an issue, I just like it clean!

**Comment by graysky2** [comment]
For starters, the current version of the script does not delete these files :p

Why would you want to get rid of them?  I believe the last two are something that systemd writes.

**Comment by nateisch** [comment]
Haha, okay no. Then its just perfect. Yes, the last two are from systemd. Thanks for the great script. You can mark this as resolved!
